  services:
      db:
        image: postgres
        container_name: db
        env_file: ./.env
        ports:
         - 5433:5433

      back-end:
        container_name: back-end
        build : ./back-end
        depends_on:
          - db
        ports:
         - 3000:3000
        
      front-end:
        container_name: front-end
        build : ./front-end
        depends_on:
          - back-end
        ports:
         - 5000:5000