  services:
      db:
        image: postgres
        container_name: db
        env_file: ./.env
        ports:
         - 5433:5432
        healthcheck:
          test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
          interval: 10s
          timeout: 5s
          retries: 5
          start_period: 5s

      back-end:
        container_name: back-end
        build : ./back-end
        depends_on:
          - db
        ports:
         - 3000:3000
        network_mode: host
        command: bash -c "flask db upgrade"
        
      front-end:
        container_name: front-end
        build : ./front-end
        depends_on:
          - back-end
        ports:
         - 5000:5000
        network_mode: host