"""initial migrate

Revision ID: 94db7622fa78
Revises: 
Create Date: 2023-01-30 06:19:05.942592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94db7622fa78'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('sinal', sa.String(), nullable=True),
    sa.Column('natureza', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cnab',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.String(), nullable=True),
    sa.Column('valor', sa.String(), nullable=True),
    sa.Column('cpf', sa.String(), nullable=True),
    sa.Column('cartao', sa.String(), nullable=True),
    sa.Column('hora', sa.String(), nullable=True),
    sa.Column('dono_da_loja', sa.String(), nullable=True),
    sa.Column('nome_da_loja', sa.String(), nullable=True),
    sa.Column('tipo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tipo_id'], ['tipo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cnab')
    op.drop_table('tipo')
    # ### end Alembic commands ###
